---

  - name: Change policy and state of SELinux
    selinux:
      state: disabled

  - include_tasks: sysctl.yml

  - name: Install epel-release
    yum:
      name: epel-release
      state: latest

  - name: Install the necessary utilities
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - openvpn
      - iperf

  - include_tasks: copy_files.yml

  - name: Start and Enable OpenVPN Server
    service:
      name: openvpn@server
      state: started
      enabled: True
    when: ansible_hostname == "tapServer" or ansible_hostname == "tunServer"

  - name: Start and Enable OpenVPN Client
    service:
      name: openvpn@client
      state: started
      enabled: True
    when: ansible_hostname == "tapClient" or ansible_hostname == "tunClient"
