---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - role: add-entry-to-hosts
      ip: '{{ master_ip }}'
      dns: '{{ master_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ slave_ip }}'
      dns: '{{ slave_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ backup_ip }}'
      dns: '{{ backup_hostname }}'

- name: setup master
  hosts: master
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - barman-repo
    - postgres11-repo
    - postgres11-server
    - postgres11-master

- name: setup slave
  hosts: slave
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - postgres11-repo
    - postgres11-server
    - postgres11-slave

- name: setup backup server
  hosts: backup
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - epel
    - postgres11-repo
    - postgres11-client
    - barman-repo
    - barman
