---

# Servers of ELK stack
- hosts: log
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - roles/log

# Web server
- hosts: web
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  roles:
    - roles/web

