# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname="web"
    web.vm.network :private_network, ip: "192.168.10.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
    end
  end

  config.vm.define "log" do |log|
    log.vm.box = "centos/7"
    log.vm.hostname="log"
    log.vm.network :private_network, ip: "192.168.10.11"
    log.vm.network "forwarded_port", guest: 5601, host: 8080
    log.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end
