---
- name: Check Nginx config
  shell: "/usr/sbin/nginx -t"
  register: nginx_config_status

- name: Nginx test status all
  debug:
    msg: "{{ nginx_config_status }}"

- name: Nginx test status
  debug:
    msg: "{{ nginx_config_status.rc }}"

- name: Service Nginx restart
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: nginx_config_status.rc == 0
