---
- name: Copy nginx repo in place.
  template:
    src: nginx.repo.j2
    dest: "{{ nginx_repo }}"
    owner: root
    group: root
    mode: 0644

- name: Install nginx
  yum:
    name: nginx
    state: present
