# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "rpm-srv" do |rpmsrv|
      rpmsrv.vm.network "forwarded_port", guest: 80, host: 8888
      rpmsrv.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      rpmsrv.vm.hostname = "rpm-srv"
      rpmsrv.vm.provision "file", source: "./nginx.spec", destination: "$HOME/nginx.spec"
      rpmsrv.vm.provision "shell", path: "rpm_create.sh"
    end
end
