# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "systemd" do |systemd|
      systemd.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      systemd.vm.hostname = "systemd"
      systemd.vm.provision "shell", path: "grep_service.sh"
      systemd.vm.provision "shell", path: "spawn_fcgi.sh"
      systemd.vm.provision "shell", path: "httpd.sh"
    end

end
