---
- name: install mail client app
  yum:
    name: mailx
    state: present
  
- name: install postfix
  yum:
    name: postfix
    state: present
  notify: restart postfix

- name: copy client config file
  template:
    src: templates/etc/postfix/main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix
...
