---
- name: install barman
  yum:
    name: barman
    state: present

- name: store connection info for barman
  template:
    src: templates/var/lib/barman/.pgpass
    dest: /var/lib/barman/.pgpass
    mode: 0600
    owner: barman
    group: barman

- name: set barman configuration
  copy:
    src: files/etc/barman.conf
    dest: /etc/barman.conf
    mode: 0644

- name: set backup configuration
  template:
    src: templates/etc/barman.d/pg.conf
    dest: /etc/barman.d/master.local.conf
    mode: 0644

- name: create replication slot
  shell: >
    barman receive-wal --create-slot {{ master_hostname }} &&
    touch /var/log/barman/slot-created
  args:
    creates: /var/log/barman/slot-created
