# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "ansible-1" do |ansible|
      ansible.vm.network "forwarded_port", guest: 8080, host: 8080
      ansible.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      ansible.vm.hostname = "ansible-1"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "nginx.yaml"
    end

end
