# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/8"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "processes" do |processes|
      processes.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
      processes.vm.hostname = "processes"
      processes.vm.provision "shell", path: "ps_ax.sh"
    end

end
