# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    config.vm.define "pam" do |pam|
      pam.vm.network "private_network", ip: "192.168.50.10"
      pam.vm.hostname = "pam"
      pam.vm.provision "shell", path: "login_weekends.sh"
      pam.vm.provision "shell", path: "docker_user.sh"
    end

end
