- hosts: flask
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  vars:
    webapp_ini_file: "{{ webapp_dest_folder }}/demo.ini"
    webapp_settings_file_path: "settings.py"
    webapp_user: "webapp"
    nginx_capable_user: "webapp"
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "mywebapp.com"
        locations:
          - location: "/"
            include: "uwsgi_params"
            uwsgi_pass: "unix://{{ webapp_dest_folder }}/demo.sock"
  tasks:
    - name: create webapp user
      user:
        name: webapp
        state: present
    - name: setup webapp
      import_role:
        name: roles/pythonwebapp
